"""create honey tokens table

Revision ID: 1079a687d564
Revises: 
Create Date: 2026-06-11 22:51:52.637596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1079a687d564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honey_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False, comment='Human-readable name shown on dashboard'),
    sa.Column('token_type', sa.Enum('API_KEY', 'DATABASE_URL', 'AWS_KEY', 'JWT_SECRET', 'SSH_KEY', 'WEBHOOK_URL', 'CUSTOM', name='token_type_enum'), nullable=False),
    sa.Column('token_value', sa.Text(), nullable=False, comment='The fake secret value planted in the environment'),
    sa.Column('description', sa.Text(), nullable=True, comment='Where this token was planted and why'),
    sa.Column('environment', sa.String(length=100), nullable=True, comment='e.g. production, staging, ci-cd'),
    sa.Column('planted_location', sa.String(length=500), nullable=True, comment='e.g. .env file, GitHub repo, S3 bucket'),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'EXPIRED', 'ARCHIVED', name='token_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of first trigger event'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honey_tokens_status'), 'honey_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_honey_tokens_token_type'), 'honey_tokens', ['token_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_honey_tokens_token_type'), table_name='honey_tokens')
    op.drop_index(op.f('ix_honey_tokens_status'), table_name='honey_tokens')
    op.drop_table('honey_tokens')
    # ### end Alembic commands ###
