"""create users table

Revision ID: 1678e02a0f6c
Revises: 2efceb2e24da
Create Date: 2026-06-22 13:58:59.905502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1678e02a0f6c'
down_revision: Union[str, None] = '2efceb2e24da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary identifier — used for login'),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hash — never store plaintext'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Disabled accounts cannot log in'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superusers can manage other users'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='Consecutive failed logins — used for lockout'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
