"""create trigger events table

Revision ID: 2efceb2e24da
Revises: 1079a687d564
Create Date: 2026-06-17 10:12:41.505627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2efceb2e24da'
down_revision: Union[str, None] = '1079a687d564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False, comment='The honey token that was accessed'),
    sa.Column('source_ip', sa.String(length=45), nullable=False, comment='IP address of accessor (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='HTTP User-Agent header from the request'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP method: GET, POST, etc.'),
    sa.Column('request_path', sa.String(length=2000), nullable=True, comment='URL path that was accessed'),
    sa.Column('additional_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible metadata — headers, geo data, etc.'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='AI-assessed severity: low, medium, high, critical'),
    sa.Column('agent_analysis', sa.Text(), nullable=True, comment='Natural language analysis from LangGraph agent'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['honey_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_events_source_ip'), 'trigger_events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_trigger_events_token_id'), 'trigger_events', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_events_token_id'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_source_ip'), table_name='trigger_events')
    op.drop_table('trigger_events')
    # ### end Alembic commands ###
